### ISSUE TITLE
今日头条使用似乎有问题，容易乱点

### ISSUE THREAD

**Issue by WANGchuang715** [GuoXiCheng/SKIP#100]

**Comment by GuoXiCheng** [comment]
不太明确你的问题，可以详细描述一下。我这边打开“今日头条”没有问题。

**Comment by WANGchuang715** [comment]
打开APP的时候没有问题，应该是在搜索栏位置退出后台后重进后会这样

**Comment by Xiaocge** [comment]
@GuoXiCheng  打开APP的时候没有问题，应该是在搜索栏位置退出后台后重进后会这样  
我也遇到这个问题了. 能修复吗

**Comment by GuoXiCheng** [comment]
> @GuoXiCheng 打开APP的时候没有问题，应该是在搜索栏位置退出后台后重进后会这样 我也遇到这个问题了. 能修复吗

已新增至config中：

https://github.com/GuoXiCheng/SKIP/blob/15026330691644004821da8ce0c796d0311c8cc8/app/src/main/assets/skip_config_v2.yaml#L109-L113

看起来是因为搜索栏下方出现推荐内容包含跳过，像是“心脏跳过快是什么原因”
