### ISSUE TITLE
华为手机点开时钟会乱点几下

### ISSUE THREAD

**Issue by garylee129** [GuoXiCheng/SKIP#130]
可能是屏幕有工作日闹钟，显示了智能跳过节假日。
1.5版本没问题，2.0出这个问题了

**Comment by GuoXiCheng** [comment]
参考：https://github.com/GuoXiCheng/SKIP/issues/84

可以打开设置里的**自动同步配置**，再重新打开一下应用

**Comment by garylee129** [comment]
关闭了重启了应用，手机也重启了，勾上按钮没啥区别喃，还是只有1.5的版本正常

**Comment by GuoXiCheng** [comment]
请更新到 [v2.1.0](https://github.com/GuoXiCheng/SKIP/releases/tag/v2.1.0) 再试

已在设置中增加是否过滤系统应用选项，可将手机时钟加入应用白名单

**Comment by egmkang** [comment]
@GuoXiCheng v2.1.1荣耀手机打开闹钟, 也会乱点几下

**Comment by GuoXiCheng** [comment]
1. 设置 → 开启“列出系统应用”
2. 应用白名单 → 把“闹钟”加入白名单

可以解决吗？

**Comment by egmkang** [comment]
@GuoXiCheng 可以了
