### ISSUE TITLE
小米手机 音乐软件乱点

### ISSUE THREAD

**Issue by r61108** [GuoXiCheng/SKIP#137]
![Screenshot_2024-02-13-13-39-25-015_com.miui.securitycenter.jpg](https://github.com/GuoXiCheng/SKIP/assets/158265832/fc15c46c-6f7a-4aa3-b97c-1d8f628e4f58)

skip已更新至最新版本
播放歌曲时 有时歌曲封面处出现广告 会一直点击并打开广告 望解决

**Comment by r61108** [comment]
![Screenshot_2024-02-14-22-09-15-191_com.miui.player-edit.jpg](https://github.com/GuoXiCheng/SKIP/assets/158265832/32aae1ae-9243-4ed1-8807-8cbe8cd32248)

**Comment by GuoXiCheng** [comment]
已更新至配置文件：https://github.com/GuoXiCheng/SKIP/blob/e74207afc963b06a3a076774a84d74d5646179f5/skip_config_v2.yaml#L89-L93

> 设置 → 开启“自动同步配置”
