### ISSUE TITLE
荣耀MagicOS 8.0 时钟闹钟乱点

### ISSUE THREAD

**Issue by shitaoA8** [GuoXiCheng/SKIP#141]
法定工作日（智能跳过节假日) 开关反复乱点
![20240218-105511](https://github.com/GuoXiCheng/SKIP/assets/53264954/055eb1e9-9e98-4a1b-9fda-69e3b6408e40)

**Comment by shitaoA8** [comment]
应用包名：com.hihonor.deskclock

**Comment by egmkang** [comment]
@shitaoA8 https://github.com/GuoXiCheng/SKIP/issues/130  参考一下这个, 自己设置一下

**Comment by shitaoA8** [comment]
> #130 参考一下这个， 自己设置一下

是的已经通过白名单解决了，希望后期作者可以直接加入到配置优化中
