### ISSUE TITLE
华尔街见闻app的启动广告不能跳过

### ISSUE THREAD

**Issue by egmkang** [GuoXiCheng/SKIP#143]
希望增加一下这个app的自动跳过
谢谢

**Comment by GuoXiCheng** [comment]
https://github.com/GuoXiCheng/SKIP/blob/f2281f41481b542bb98ec80a0f0ad9f06eb06d64/app/src/main/assets/skip_config_v2.yaml#L94-L97

**Comment by crazysong** [comment]
@GuoXiCheng miui14能用吗？在note12tpro上试了很久，好像开启不了？

**Comment by crazysong** [comment]
@GuoXiCheng 嗯，原来是需要在已下载应用中启用本程序。开启了，感谢！
