### ISSUE TITLE
小米HyperOS系统无法使用

### ISSUE THREAD

**Issue by chensimmons** [GuoXiCheng/SKIP#154]
直接点击启动，跳到无障碍设置，把所有无障碍设置都打开了，主界面还是没有显示已启动，再点击启动，还是跳到无障碍设置，无法启动

更新，看到关闭的issue了，原来也有相关问题，我尝试下

**Comment by lrs95** [comment]
我红米K70Pro能使用啊，也是澎湃OS，跳到无障碍页面你要点击已下载的应用，然后找SKIP，点启用等10秒勾选确认再返回就行了
