### ISSUE TITLE
一款叫生日助手的app没法跳过

### ISSUE THREAD

**Issue by lrs95** [GuoXiCheng/SKIP#160]
这app即使开了永久会员也跳过不了开屏广告

**Comment by lrs95** [comment]
还有个小时工记账，这app开屏广告好像有两种，如图前者无法跳过，后者可以跳过
![Screenshot_2024-06-16-22-16-21-190_com miui secur](https://github.com/GuoXiCheng/SKIP/assets/24587454/9cd9b42b-9faf-4822-84ad-bb30be58a707)
![Screenshot_2024-06-16-22-17-15-199_com miui media](https://github.com/GuoXiCheng/SKIP/assets/24587454/5e736a72-a92a-4e84-9c52-48a6a89e8fb9)

**Comment by GuoXiCheng** [comment]
已更新配置

https://github.com/GuoXiCheng/SKIP/blob/4211f7eee1e00ecb2c8a99a7568f6d87b1a950dd/app/src/main/assets/skip_config_v2.yaml#L130-L142
