### ISSUE TITLE
The status bar is not reversed. 

### ISSUE THREAD

**Issue by Boomz123** [GuoXiCheng/SKIP#163]
The status bar is not reversed. Resulting in the inability to read the time and other information in the status bar
![Screenshot_20240624_201050_com android skip](https://github.com/GuoXiCheng/SKIP/assets/166996243/71e630e2-bb31-4043-b039-cdb4362ce810)

**Comment by Boomz123** [comment]
![Uploading Screenshot_20240624_201050_com.android.skip.jpg…]()

**Comment by GuoXiCheng** [comment]
Redmi K60 is displayed normally
