### ISSUE TITLE
可否像轻启动那样有个设置可以设置成设备管理员，这样就不容易被杀无障碍了

### ISSUE THREAD

**Issue by yixingzhiwang** [GuoXiCheng/SKIP#164]

**Comment by GuoXiCheng** [comment]
不太知道，设备管理员是什么设置？

**Comment by yixingzhiwang** [comment]
你下个轻启动看看，里面设置就有这个



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月16日(周二) 晚上7:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [GuoXiCheng/SKIP] 可否像轻启动那样有个设置可以设置成设备管理员，这样就不容易被杀无障碍了 (Issue #164)




 
不太知道，设备管理员是什么设置？

**Comment by GuoXiCheng** [comment]
直接百度根据对应机型的应用保活教程设置即可
