### ISSUE TITLE
cellular无法跳过

### ISSUE THREAD

**Issue by biange200** [GuoXiCheng/SKIP#172]
![Screenshot_20240723_083808.jpg](https://github.com/user-attachments/assets/fcb29a9f-d47f-4463-80f7-21f832278416)

![Screenshot_20240723_083814.jpg](https://github.com/user-attachments/assets/19ba17d3-615c-4ff7-9bb1-3eb9fe984c77)

**Comment by GuoXiCheng** [comment]
已更新配置

https://github.com/GuoXiCheng/SKIP/blob/c09416cdbb5c041bae3d2cf6406d12f2f4f82e80/app/src/main/assets/skip_config_v2.yaml#L126-L130

**Comment by biange200** [comment]
![Screenshot_20240726_085943.jpg](https://github.com/user-attachments/assets/2e9fe0d7-c856-4e82-997b-18937ebe0bb5)

这个后缀z的也是无法跳过
