### ISSUE TITLE
关于和去广告软件一起用的问题

### ISSUE THREAD

**Issue by biange200** [GuoXiCheng/SKIP#173]
我用过rethinkdns blokada pdnf这几个去广告软件，发现和skip一起用,skip有时候可以跳过开屏广告有时候会失效，在同一个软件上
我还把rethinkdns skip双方互相加白名单也没用
目前用的是rethinkdns,
https://www.rethinkdns.com/
希望作者大大解决下问题

**Comment by GuoXiCheng** [comment]
只要“SKIP”的无障碍服务正常工作应该就可以
