### ISSUE TITLE
CSDN无法跳过

### ISSUE THREAD

**Issue by fzhz666** [GuoXiCheng/SKIP#180]

**Comment by fzhz666** [comment]
有一个点要提示一下，例如CSDN的开屏广告是含有两个的
一个是要按掉圆形的跳过按钮，一个是要按掉长圆形的按钮，都是存在5秒。
有可能只关掉第一个圆形的，还有一个长圆形的没关掉。

目前来啦，长圆形的按钮跳过并没有完成似乎
![微信图片_20240728184922](https://github.com/user-attachments/assets/7f2d4418-d3bc-4e1f-b5c0-e76d90d9b7f1)

**Comment by GuoXiCheng** [comment]
圆形的：https://github.com/GuoXiCheng/SKIP/commit/1dd9a8d5503f217e0e2eb6390546508d37acc767
