### ISSUE TITLE
保活的一点疑惑

### ISSUE THREAD

**Issue by SpaceA001** [GuoXiCheng/SKIP#196]
荣耀九的手机，在后台多任务界面中没有skip的窗口，锁定不了，这个能解决吗

**Comment by GuoXiCheng** [comment]
应该可以

**Comment by SpaceA001** [comment]
就是这样的。现在的问题是过一段时间skip会自动关闭，但是我无障碍里面的服务是开启的。
抱歉麻烦您了。

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GuoXiCheng** [comment]
你是发了图片？我看不到

**Comment by SpaceA001** [comment]
你好，就是一个演示的视频。
我想说的就是我的skip在多任务界面看不见；
有时候过一段时间就关闭了，但是无障碍服务还是打开的，甚至会skip已启动的时候没作用；
harmony OS 2.0.0

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by GuoXiCheng** [comment]
如果不是原生安卓，可能运行起来不是很好

请更新到新版再试一下

https://github.com/GuoXiCheng/SKIP/releases/tag/v3.0.0

**Comment by SpaceA001** [comment]
非常感谢，已经可以用了，麻烦您了。
感谢SKIP为安卓用户带来的巨大便利！

发件人: GuoXiCheng ***@***.***>
日期: 星期二, 2024年10月8日 09:22
收件人: GuoXiCheng/SKIP ***@***.***>
抄送: SpaceA001 ***@***.***>, Author ***@***.***>
主题: Re: [GuoXiCheng/SKIP] 保活的一点疑惑 (Issue #196)

如果不是原生安卓，可能运行起来不是很好

请更新到新版再试一下

https://github.com/GuoXiCheng/SKIP/releases/tag/v3.0.0

―
