### ISSUE TITLE
摩托罗拉手机安装后无法打开应用

### ISSUE THREAD

**Issue by Way2010** [GuoXiCheng/SKIP#286]
![Screenshot_20241104-154216_Moto 应用启动器.png](https://github.com/user-attachments/assets/c264932e-27be-45a3-a97e-dbef4e6e51cb)

![Screenshot_20241104-154226_Moto 应用启动器.png](https://github.com/user-attachments/assets/6ff5e024-030e-4693-96f7-210f08a16bfa)

**Comment by GuoXiCheng** [comment]
找到「系统设置」，找到「应用管理」，找到并点击「SKIP」，点击「右上角」，点击「允许受限制的设置」
