### ISSUE TITLE
当网盘软件页面中有跳过两字的APP时，打开APP会导致SKIP自动点击下载并安装。。。

### ISSUE THREAD

**Issue by pinoren** [GuoXiCheng/SKIP#38]
当网盘软件页面中有名称包含跳过两字的APP时，打开APP会导致SKIP无限重复自动点击下载并安装，取消后会重复循环点击安装。

是否可以增加判断？或者可以设置排除某软件？

**Comment by GuoXiCheng** [comment]
可以添加一个应用白名单的功能，过滤掉某些APP，应该可以解决你的问题

**Comment by pinoren** [comment]
就真的太感谢了，实不相瞒，我是在网盘里放了您这个软件，并且给他起名叫跳过广告，然后就出现了这个bug，哈哈。

**Comment by GuoXiCheng** [comment]
请更新至v1.4版本再试

**Comment by pinoren** [comment]
收到！非常非常感谢！

**Comment by pinoren** [comment]
经过测试，软件启动的时候会显示一个，更新配置成功的提示，然后没有地方可以设置，忽略哪个软件这些的地方，然后他依然在网盘里面不停的重复下载带有跳过两字的软件。。。。

**Comment by pinoren** [comment]
没有广告，是群晖网盘的客户端。。。

**Comment by GuoXiCheng** [comment]
> 没有广告，是群晖网盘的客户端。。。

可以提供一下应用的包名，我再更新到配置文件中
