### ISSUE TITLE
无法开启无障碍模式

### ISSUE THREAD

**Issue by Zhangxxl** [GuoXiCheng/SKIP#41]
![Screenshot_20230927-223355](https://github.com/GuoXiCheng/SKIP/assets/18618523/e022eee2-8323-42f0-a75e-f405677e4a7a)
如图，列表显示为灰色，点击提示受限制的设置，但不是所有应用的无障碍都无法打开，轻启动，李跳跳，搜狗输入法，百度输入法这些都可以开启，skip mt管理器 es文件浏览器，清浊这些无法打开，设备是 moto x30 Android13

**Comment by GuoXiCheng** [comment]
设备的问题我无法解决，我使用的是Redmi
