### ISSUE TITLE
一个小疑问

### ISSUE THREAD

**Issue by k2y1982** [GuoXiCheng/SKIP#55]
跳过广告的速度确实很快，点个赞。
不过没提示，我都不知道是软件起作用了，还是根本没有广告了。
1.3.2有个在线更新配置的功能，国内容易连不上，可以改成镜像站的地址吗，再加个点击更新的按钮，免得被人说自动联网。

**Comment by GuoXiCheng** [comment]
1. 跳过提示原本有的，**1.3.2**版本里我注释掉了，可以再加回来，不过需要开启“**允许通知**”的权限才能在软件外看到提示
2. 配置文件是放在[skip_config_v1.json](https://github.com/GuoXiCheng/SKIP/blob/main/app/src/main/res/raw/skip_config_v1.json)，镜像站没弄过（不知道有没有免费的），还需要考虑与镜像站配置的自动同步，不然维护有点麻烦，可以再研究一下
3. 更新按钮可以加

**Comment by k2y1982** [comment]
感谢你的回复，期待下次更新

**Comment by GuoXiCheng** [comment]
请更新至v1.4版本再试
