### ISSUE TITLE
闹钟乱闪

### ISSUE THREAD

**Issue by Chchm7** [GuoXiCheng/SKIP#64]
HUAWEI MATE40pro+，打开闹钟，闪动。1.3.4b版。谢谢！

**Comment by GuoXiCheng** [comment]
闹钟应该没有广告吧，可以提供一下应用名称和包名，我再添加到配置中

**Comment by Chchm7** [comment]
> 闹钟应该没有广告吧，可以提供一下应用名称和包名，我再添加到配置中

谢谢！
已发邮件给您！

**Comment by GuoXiCheng** [comment]
已更新

**Comment by Chchm7** [comment]
谢谢！看到了。😆
