### ISSUE TITLE
华为手机闹钟识别依旧有问题

### ISSUE THREAD

**Issue by iShawn-lee** [GuoXiCheng/SKIP#84]
华为手机mate30pro，鸿蒙4.0系统，用skip v1.5版本，打开手机自带闹钟时问题有两个：
1、在打开闹钟后会自动识别智能跳过法定节假日字样，然后自动点进去疯狂点点点......
2、没有智能跳过法定节假日字样时，会自动识别世界时钟字样然后帮你点进该选项卡中......
我看这些问题在过去的issues里有两个用户也遇到了，很可惜最新版本依旧未解决这些Bug
依旧感谢您在百忙中开发该开源App!很实用，谢谢！

**Comment by GuoXiCheng** [comment]
感谢你的反馈！

我有在config中配置华为时钟，如果我的应用包名称配置无误的话，理论上来说应该就不会执行点击的动作吧

https://github.com/GuoXiCheng/SKIP/blob/a2375cf548bf277a55d28c028eb1e2e0d3abf2d5/skip_config.yaml#L52-L54

**Comment by GuoXiCheng** [comment]
> 华为手机mate30pro，鸿蒙4.0系统，用skip v1.5版本，打开手机自带闹钟时问题有两个： 1、在打开闹钟后会自动识别智能跳过法定节假日字样，然后自动点进去疯狂点点点...... 2、没有智能跳过法定节假日字样时，会自动识别世界时钟字样然后帮你点进该选项卡中...... 我看这些问题在过去的issues里有两个用户也遇到了，很可惜最新版本依旧未解决这些Bug 依旧感谢您在百忙中开发该开源App!很实用，谢谢！

我猜测是包名没有填写正确，我更新了config：
https://github.com/GuoXiCheng/SKIP/blob/22f352e96688b983c5747a91e27f356ca17bf90c/skip_config.yaml#L52-L54

**Comment by iShawn-lee** [comment]
问题已修复，感谢！
