### ISSUE TITLE
跳过等待时间过长

### ISSUE THREAD

**Issue by KIITTID** [GuoXiCheng/SKIP#85]
跳过开屏广告要等1s+，有点儿久了。

**Comment by GuoXiCheng** [comment]
不知道你说的是哪个APP

**Comment by KIITTID** [comment]
> 不知道你说的是哪个APP

今日头条

**Comment by GuoXiCheng** [comment]
> > 不知道你说的是哪个APP
> 
> 今日头条

没有出现你说的情况，很快就跳过了，我是RedmiK60
