### ISSUE TITLE
如果聊天窗口含有“跳过”等字，会出现误判一直点击的情况

### ISSUE THREAD

**Issue by zhaodice** [GuoXiCheng/SKIP#89]
比如qq聊天，说跳过这两个字，就会被程序误认为是广告跳过按钮，一直点

**Comment by GuoXiCheng** [comment]
qq好像没有开屏广告吧，可以设置max_click_count=0来屏蔽点击的动作

**Comment by GuoXiCheng** [comment]
那其实影响比较小吧，真正比较讨厌的是那种你每次打开APP，甚至只是重新从后台切到前台都会出现的开屏广告。

**Comment by GuoXiCheng** [comment]
1. 可以做，但我的判断是目前价值不高
2. 有的情况是“跳过“，有的情况是“跳过广告”，有的情况会是“跳过广告 5s”带倒计时，根据长度不是很好去做限制。我做法是在进入APP后执行30次扫描动作，30次之后不会再有任何点击动作。因此可以通过max_click_count来限制它的点击次数在0或者1。
4. 新增询问不要，我希望这个APP应该是无感的存在，不应有过多的打扰
5. 让用户添加规则的价值不高，一般用户的话让他去开启无障碍服务可能都已经很困难了。如果是有开发经验的用户，可以直接提交PR或Issue来更新规则

我的计划下一个Release可能会是去重构主界面的UI。

**Comment by GuoXiCheng** [comment]
> 其次，这不是最终方案，最终还得通过不断增强规则，在规则的束缚下100%可信的情况下可以实现自动跳过，才是硬道理。（目前你的规则太弱了，误判率太高了，很适合这种）
> 
> 我是这样想的，通过强编码ID，坐标，包名等显式定义的规则，可以无须询问用户，直接操作。 通过关键词，模糊查询，甚至可能是深度学习等方式的非确定性规则，可以通过弹窗询问（需要通过设置打开，默认还是按你原本的行为），减少误判

也许你可以看看这个项目 https://github.com/gkd-kit/gkd  已经实现了不错的模糊查询
