### ISSUE TITLE
无障碍服务总是自己关掉

### ISSUE THREAD

**Issue by Chchm7** [GuoXiCheng/SKIP#93]
为什么无障碍服务总是自己关掉，是手机策略原因还是其他因素？

**Comment by GuoXiCheng** [comment]
是因为被系统杀进程，所以要做后台保活，不同品牌的设置方式不太一样。
基本思路是要设置：允许自启动、后台进程锁定、加入应用白名单等等。
具体的可以根据你的手机品牌型号自行百度应用后台保活方式。
