### ISSUE TITLE
荣耀80gt有bug

### ISSUE THREAD

**Issue by Xiaobaishushu25** [GuoXiCheng/SKIP#94]
不知道为什么一直自动点击另一个软件，桌面上也没有跳过两个字

https://github.com/GuoXiCheng/SKIP/assets/76581880/9735735b-91d3-46d9-9d63-4b67894efed6

**Comment by GuoXiCheng** [comment]
不一定说要能看到“跳过”两个字，只要发现节点的text="跳过"就会被点击。
解决方法可以是在配置文件中去屏蔽掉你的桌面应用，如果你知道你桌面应用的包名称的话，可以提供给我。
（也许后续再增加一个白名单的功能更好）

**Comment by Xiaobaishushu25** [comment]
> 不一定说要能看到“跳过”两个字，只要发现节点的text="跳过"就会被点击。 解决方法可以是在配置文件中去屏蔽掉你的桌面应用，如果你知道你桌面应用的包名称的话，可以提供给我。 （也许后续再增加一个白名单的功能更好）

不知道包名称哎😂
