### ISSUE TITLE
虎扑、百度网盘、轻阅等开屏广告无法跳过

### ISSUE THREAD

**Issue by Xiaobaishushu25** [GuoXiCheng/SKIP#98]
![Screenshot_20231206_161341](https://github.com/GuoXiCheng/SKIP/assets/76581880/027b02eb-26fd-4deb-b278-f98f7a1674c2)
![Screenshot_20231206_161551](https://github.com/GuoXiCheng/SKIP/assets/76581880/29c72881-1d2f-4003-b9d7-9e596552e913)
![Screenshot_20231206_161638](https://github.com/GuoXiCheng/SKIP/assets/76581880/54a10256-ac85-4760-9f22-256f4a9cab62)
我发现都是这种圆形的跳过按钮无法自动点击😀

**Comment by GuoXiCheng** [comment]
是的，需要根据它的id来进行跳过

**Comment by Xiaobaishushu25** [comment]
> 是的，需要根据它的id来进行跳过

大佬，我自己尝试了一下增加虎扑：
![image](https://github.com/GuoXiCheng/SKIP/assets/76581880/d09a3706-08b4-4a28-b1d9-4b68dc8883ad)
我是使用iQOONeo3进行调试的，屏幕分辨率是1080*2408，我在资源文件下的配置文件增添了：
# 虎扑
- package_name: com.hupu.games
  skip_id: com.byted.pangle:id/tt_splash_skip_btn
  skip_bounds:
    - 1080,2408#912,156,1032,276
连接as在真机测试发现还是无法跳过虎扑广告，知乎贴吧等可以正常跳过，而且csdn的广告也无法跳过，我看配置文件里面也有：# CSDN
- package_name: net.csdn.csdnplus
  skip_id: com.byted.pangle.m:id/tt_splash_skip_btn
这是什么原因呢？

**Comment by GuoXiCheng** [comment]
1. 虎扑可以抓到id，配置id就应该可以跳过了。
另外注意一下，如果你只是修改了本地的config，可以log一下看看它是**加载的本地的配置还是远端的配置**。
如果你使用的2.x版本，config有所变化：[skip_config_v2](https://github.com/GuoXiCheng/SKIP/blob/main/app/src/main/assets/skip_config_v2.yaml)

2. CSDN有点变化，我最近调试发现它无法抓到id了，开屏界面是一整个view，可能是因为：[Not Supported App List](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/main/_source/NotSupportedList/NotSupportedList.md)

**Comment by Xiaobaishushu25** [comment]
> 1. 虎扑可以抓到id，配置id就应该可以跳过了。
>    另外注意一下，如果你只是修改了本地的config，可以log一下看看它是**加载的本地的配置还是远端的配置**。
>    如果你使用的2.x版本，config有所变化：[skip_config_v2](https://github.com/GuoXiCheng/SKIP/blob/main/app/src/main/assets/skip_config_v2.yaml)
> 2. CSDN有点变化，我最近调试发现它无法抓到id了，开屏界面是一整个view，可能是因为：[Not Supported App List](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/main/_source/NotSupportedList/NotSupportedList.md)

成功跳过虎扑广告了！！我昨天没注意NewMainActivity是用的v2版本的，在v2的配置文件增添了：
# 虎扑
- packageName: com.hupu.games
  skipIds:
    - id: com.byted.pangle:id/tt_splash_skip_btn
  skipBounds:
    - bound: 912,156,1032,276
      resolution: 1080,2308
可以了，非常感谢作者耐心及时的回复。
另外我还有一个疑惑：我看应用一开始运行会先读取本地config，当更新远端配置时好像是整个完全替换本地配置掉而不是互补的？但是我鲨掉skip重新打开后还是可以跳过虎扑的广告，不知道是没自动更新远端配置还是什么原因.

**Comment by GuoXiCheng** [comment]
> > 1. 虎扑可以抓到id，配置id就应该可以跳过了。
> >    另外注意一下，如果你只是修改了本地的config，可以log一下看看它是**加载的本地的配置还是远端的配置**。
> >    如果你使用的2.x版本，config有所变化：[skip_config_v2](https://github.com/GuoXiCheng/SKIP/blob/main/app/src/main/assets/skip_config_v2.yaml)
> > 2. CSDN有点变化，我最近调试发现它无法抓到id了，开屏界面是一整个view，可能是因为：[Not Supported App List](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/main/_source/NotSupportedList/NotSupportedList.md)
> 
> 成功跳过虎扑广告了！！我昨天没注意NewMainActivity是用的v2版本的，在v2的配置文件增添了：
> 
> # 虎扑
> * packageName: com.hupu.games
>   skipIds:
>   
>   * id: com.byted.pangle:id/tt_splash_skip_btn
>     skipBounds:
>   * bound: 912,156,1032,276
>     resolution: 1080,2308
>     可以了，非常感谢作者耐心及时的回复。
>     另外我还有一个疑惑：我看应用一开始运行会先读取本地config，当更新远端配置时好像是整个完全替换本地配置掉而不是互补的？但是我鲨掉skip重新打开后还是可以跳过虎扑的广告，不知道是没自动更新远端配置还是什么原因.

1. 已追加到skip_config_v2.yaml中：https://github.com/GuoXiCheng/SKIP/blob/a1ad0f8a982fb933c0a3fe3fd69c6eca67a27e12/app/src/main/assets/skip_config_v2.yaml#L73-L79

2. **首次**打开应用时会加载本地配置，需要在SKIP的设置中开启：“自动同步配置”，这样才会在**之后**打开应用时将配置更新为远端配置，并不再加载本地的配置

**Comment by GuoXiCheng** [comment]
> > 1. 虎扑可以抓到id，配置id就应该可以跳过了。
> >    另外注意一下，如果你只是修改了本地的config，可以log一下看看它是**加载的本地的配置还是远端的配置**。
> >    如果你使用的2.x版本，config有所变化：[skip_config_v2](https://github.com/GuoXiCheng/SKIP/blob/main/app/src/main/assets/skip_config_v2.yaml)
> > 2. CSDN有点变化，我最近调试发现它无法抓到id了，开屏界面是一整个view，可能是因为：[Not Supported App List](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/main/_source/NotSupportedList/NotSupportedList.md)
> 
> 还有一个问题，v2的配置文件没有最大点击数这个属性了吗，因为虽然有了一个白名单功能，但是里面没有荣耀自带的时钟应用，打开时钟时还是会乱点。

白名单中列出的应用，除去了系统自带应用，因为我感觉列出系统自带应用的话应用太多了https://github.com/GuoXiCheng/SKIP/blob/a1ad0f8a982fb933c0a3fe3fd69c6eca67a27e12/app/src/main/java/com/android/skip/WhitelistActivity.kt#L49-L51

我在skip_config_v2中添加如下配置应该可以解决你的问题：
https://github.com/GuoXiCheng/SKIP/blob/312e5520783d320b48c4879de8ec7344e72fc2ea/app/src/main/assets/skip_config_v2.yaml#L81-L85

**Comment by Xiaobaishushu25** [comment]
> > > 1. 虎扑可以抓到id，配置id就应该可以跳过了。
> > >    另外注意一下，如果你只是修改了本地的config，可以log一下看看它是**加载的本地的配置还是远端的配置**。
> > >    如果你使用的2.x版本，config有所变化：[skip_config_v2](https://github.com/GuoXiCheng/SKIP/blob/main/app/src/main/assets/skip_config_v2.yaml)
> > > 2. CSDN有点变化，我最近调试发现它无法抓到id了，开屏界面是一整个view，可能是因为：[Not Supported App List](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/main/_source/NotSupportedList/NotSupportedList.md)
> > 
> > 
> > 还有一个问题，v2的配置文件没有最大点击数这个属性了吗，因为虽然有了一个白名单功能，但是里面没有荣耀自带的时钟应用，打开时钟时还是会乱点。
> 
> 白名单中列出的应用，除去了系统自带应用，因为我感觉列出系统自带应用的话应用太多了
> 
> https://github.com/GuoXiCheng/SKIP/blob/a1ad0f8a982fb933c0a3fe3fd69c6eca67a27e12/app/src/main/java/com/android/skip/WhitelistActivity.kt#L49-L51
> 
> 我在skip_config_v2中添加如下配置应该可以解决你的问题：
> 
> https://github.com/GuoXiCheng/SKIP/blob/312e5520783d320b48c4879de8ec7344e72fc2ea/app/src/main/assets/skip_config_v2.yaml#L81-L85


> > > 1. 虎扑可以抓到id，配置id就应该可以跳过了。
> > >    另外注意一下，如果你只是修改了本地的config，可以log一下看看它是**加载的本地的配置还是远端的配置**。
> > >    如果你使用的2.x版本，config有所变化：[skip_config_v2](https://github.com/GuoXiCheng/SKIP/blob/main/app/src/main/assets/skip_config_v2.yaml)
> > > 2. CSDN有点变化，我最近调试发现它无法抓到id了，开屏界面是一整个view，可能是因为：[Not Supported App List](https://github.com/Snoopy1866/LiTiaotiao-Custom-Rules/blob/main/_source/NotSupportedList/NotSupportedList.md)
> > 
> > 
> > 成功跳过虎扑广告了！！我昨天没注意NewMainActivity是用的v2版本的，在v2的配置文件增添了：
> > # 虎扑
> > 
> > * packageName: com.hupu.games
> >   skipIds:
> >   
> >   * id: com.byted.pangle:id/tt_splash_skip_btn
> >     skipBounds:
> >   * bound: 912,156,1032,276
> >     resolution: 1080,2308
> >     可以了，非常感谢作者耐心及时的回复。
> >     另外我还有一个疑惑：我看应用一开始运行会先读取本地config，当更新远端配置时好像是整个完全替换本地配置掉而不是互补的？但是我鲨掉skip重新打开后还是可以跳过虎扑的广告，不知道是没自动更新远端配置还是什么原因.
> 
> 1. 已追加到skip_config_v2.yaml中：https://github.com/GuoXiCheng/SKIP/blob/a1ad0f8a982fb933c0a3fe3fd69c6eca67a27e12/app/src/main/assets/skip_config_v2.yaml#L73-L79
> 2. **首次**打开应用时会加载本地配置，需要在SKIP的设置中开启：“自动同步配置”，这样才会在**之后**打开应用时将配置更新为远端配置，并不再加载本地的配置

大佬你好，我昨天晚上发现虎扑又不能正常跳过，搞了半天发现是开屏广告跳过按钮的id和位置变了：
![image](https://github.com/GuoXiCheng/SKIP/assets/76581880/c97bba09-8e3e-44b0-adec-bff09e7b17e9)
虽然id变了，但是位置没变太多，我找到BoundsHandler中发现是node包含配置区域才加入点击列表，我觉得改成node与配置区域相交会不会更好一点，这样鲁棒性更强，只要大致区域对了就可以我试了一下加上相交可以继续正常跳过虎扑。
第二个是每次更新远端配置不是完全替换当前配置，而是对比更新、增添会不会更好一点，毕竟作者不一定能非常及时的实时更新配置文件，有的同学源码拉下去自己加了点配置不至于被覆盖失效（比如我..）。
不知道你怎么看这两点，如果可以的话，我可以提个pr不（主要就是上面两点+轻阅和百度网盘的配置）😀

**Comment by GuoXiCheng** [comment]
1. 看你图中红框的位置，应该是没有准确的捕捉到“跳过”节点（或者无法捕捉），如果改为相交而不是严格包含的话，我怕是会增加误触的概率，比如你已经进入应用主界面了，还是继续在被点击
2. 增量更新配置我觉得也可以做吧，比如 by packageName 去新增或更新配置而不是替换掉整个配置文件

**Comment by GuoXiCheng** [comment]
其实还有一个相比“相交方式”更加简单直接的方式可以无视他节点是否存在，就是直接点击固定的坐标（相对坐标）。
但是这种方式需要一个严格的判断条件来辨别当前是否处于开屏广告界面（通过activity name或者别的什么），要不然发生误触是必然的。

**Comment by Xiaobaishushu25** [comment]
> 其实还有一个相比“相交方式”更加简单直接的方式可以无视他节点是否存在，就是直接点击固定的坐标（相对坐标）。 但是这种方式需要一个严格的判断条件来辨别当前是否处于开屏广告界面（通过activity name或者别的什么），要不然发生误触是必然的。

如何判断当前是否处于开屏广告界面我就不懂了，没学过安卓开发😰

**Comment by wdscxsj** [comment]
建议增加一个手工同步配置的按钮，按需更新。

**Comment by GuoXiCheng** [comment]
请更新到新版再试

https://github.com/GuoXiCheng/SKIP/releases/tag/v3.0.0
