### ISSUE TITLE
安卓14用不了。

### ISSUE THREAD

**Issue by zjqtycx** [GuoXiCheng/SKIP#99]

**Comment by zjqtycx** [comment]
任意一个app都不行

**Comment by GuoXiCheng** [comment]
HyperOS系统或升级至Android14无法正常使用无障碍服务可尝试使用以下两种方法：
1. 长按图标，点击“应用信息”，设置“省电策略”为“无限制”。
2. 系统设置搜索“屏幕时间管理”，右上角“停用屏幕时间管理”。

如果以上两种方法依然不行，可尝试以下方法：
1. 打开系统设置
2. 点击“我的设备”，“全部参数与信息”；
3. 连续点击“MIUI版本”，直至提示“处于开发者模式”；
4. 返回设置主页，点击“更多设置”，“开发者选项”；
5. 滑动到底部，找到“启动MIUI优化”；
6. 关闭“MIUI优化”，再打开“MIUI优化”；
7. 测试无障碍服务是否正常

注意：
1. 重启手机后将失效，需要重新关闭打开“MIUI优化”；
2. 该操作将重置部分设置，例如：输入法、超级壁纸；
